# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               宋辰文
tagline:             '的博客'
description:         '宋辰文<br />Android & iOS 开发者<br />比太钱包联合创始人'
url:                 https://songchenwen.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              宋辰文
  url:               https://twitter.com/emptyzone0
  email:             emptyzone0@gmail.com

# Custom vars
version:             1.0.0

excerpt_separator:   "<!-- more -->"

enforce_ssl: songchenwen.github.io

prose:
  rooturl: '_posts'
  siteurl: 'https://songchenwen.github.io/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Category"
          value: "Tech"          
          placeholder: "Choose Category"
          options:
            - name: "Tech"
              value: "Tech"
            - name: "Life"
              value: "Life"
            - name: "Read"
              value: "Read"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: true