# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               宋辰文
tagline:             '的博客'
description:         'Android & iOS 开发者<br />比太钱包联合创始人'
url:                 https://songchenwen.github.io
logo:                site-logo.png
default_bg:          default_bg.jpg
paginate:            5


owner:
  name:              宋辰文
  avatar:            songchenwen.png
  email:             sanvinsung@gmail.com
  description:       'Android & iOS 开发者<br />比太钱包联合创始人'
  twitter:           songchenwen
  github:            songchenwen
  stackexchange:     https://stackexchange.com/users/2545861/songchenwen

disqus_shortname: garyblog

search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:              80
# Turn on or off the fin animations in the header and footer
triangleheader:   true
animated_fins:    true
# Specify the fin color in RGB value
fin_color:        "255,255,255"

links: 
  - title: Home
    url: /
    icon: home
  - title: Projects
    url: /projects/
  - title: Categories
    url: /categories/
  - title: Tags
    url: /tags/

markdown: redcarpet

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom vars
version:             2.0.0

excerpt_separator:   "<!-- more -->"

enforce_ssl: songchenwen.github.io

prose:
  rooturl: '_posts'
  siteurl: 'https://songchenwen.github.io/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "select"
          label: "Category"
          value: "Tech"          
          placeholder: "Choose Category"
          options:
            - name: "Tech"
              value: "Tech"
            - name: "Life"
              value: "Life"
            - name: "Read"
              value: "Read"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: true